### ISSUE TITLE
Add general wikidata fetcher function supporting more than 50 ids 

### ISSUE THREAD

**Issue by mshd** [ogroppo/wikiforest#30]
I would like a common fetcher function [based on this](https://github.com/dataprick/wikitree/blob/master/controllers/wikidata.js)
It should support more than 50 ids, make multiple requests and give them back merged.
You started using axios, I used fetch earlier.

**Comment by ogroppo** [comment]
What exactly is the problem here? do you mean getManyEntities accepts max 50 elements? also I tries getManyEntities at the beginning and it seemed not working for the "infamous" cors error, which might have been something else that is not communicated.
fetch or axios, absolutely the same as both return promise, axios returns a nicer object back with response codes and formatted json in the "data" prop but other than that you could even mix them

**Comment by ogroppo** [comment]
covered by ```wikidata/getItems.js```
